defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.0
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
            name: Install Dependencies
            command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
            name: Lint TypeScript code
            command: npm run lint

      - run:
          name: Test TypeScript code
          command: npm run test:cover

      - run:
          name: Submit coverage report to Coveralls.io
          command: npm run coveralls

      - run:
          name: Build code
          command: npm run build:npm

  publish:
    <<: *defaults
    steps:
      - run:
          name: Write NPM Token to ~/.npmrc
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

      - run:
          name: Install dot-json package
          command: sudo npm install -g dot-json

      - run:
          name: Write version to package.json
          command: $(npm bin)/dot-json package.json version ${CIRCLE_TAG:1}

      - run:
          name: Publish to NPM
          command: npm publish --access=public

workflows:
  version: 2
  build-publish:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/

